layout_spectrum: 0.927099
typography_spectrum: 0.3200616
color:
  saturation: 0.6897062
  lightness: 0.02417291
  brandStrength: 1
  brandColors:
    - '#326A2B'
    - '#EEAA0B'
    - '#FBFFF9'
    - '#ECD2A5'
    - '#887702'
  rhythmicContrast: 0.01537924
name: Star-Waffles
