layout_spectrum: 0
typography_spectrum: 0.3200616
color:
  saturation: 0.6200717
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#326A2B'
    - '#EEAA0B'
    - '#FBFFF9'
    - '#ECD2A5'
    - '#887702'
  rhythmicContrast: 0.344086
name: Star-Waffles
